// <auto-generated>
//     Generated from the CREATE TABLE statement for [dbo].[Import_Update].
//     71 columns. Regenerate rather than editing by hand.
// </auto-generated>

namespace ProVest.Admin.Api.Data;

/// <summary>
/// SQL fragments for [dbo].[Import_Update]. Every value reaches the database as a
/// parameter; nothing here is built from user input.
/// </summary>
internal static class ImportUpdateSql
{
    public const string Table = "dbo.Import_Update";
    public const string Alias = "t";

    /// <summary>All 71 columns, for the detail record.</summary>
    public const string DetailColumns = @"
           t.[id],
           t.[client_id],
           t.[lawfirm_filenumber],
           t.[3rdparty_filenumber] AS thirdparty_filenumber,
           t.[plaintiff],
           t.[plaintiff2],
           t.[defendant],
           t.[defendant2],
           t.[document_code],
           t.[document_type],
           t.[index_number],
           t.[court_name],
           t.[court_type],
           t.[court_county],
           t.[court_city],
           t.[court_state],
           t.[court_zip],
           t.[servee_last_name],
           t.[servee_name],
           t.[servee_address],
           t.[servee_apt],
           t.[servee_city],
           t.[servee_state],
           t.[servee_zip],
           t.[servee_last_name2],
           t.[servee_name2],
           t.[servee_address2],
           t.[servee_apt2],
           t.[servee_city2],
           t.[servee_state2],
           t.[servee_zip2],
           t.[employer_name],
           t.[employer_address1],
           t.[employer_address2],
           t.[employer_city],
           t.[employer_state],
           t.[employer_zip],
           t.[special_instructions],
           t.[additional_info1],
           t.[additional_info2],
           t.[additional_info3],
           t.[additional_info4],
           t.[additional_info5],
           t.[kasebilling_checknum],
           t.[kasebilling_amt],
           t.[date_kase_filed],
           t.[court_date],
           t.[court_time],
           t.[court_room],
           t.[date_due],
           t.[client_ref],
           t.[creditor],
           t.[chargeoff_date],
           t.[suit_amt],
           t.[principal],
           t.[interest],
           t.[court_cost],
           t.[atty_cost],
           t.[client_data1],
           t.[client_data2],
           t.[client_data3],
           t.[client_data4],
           t.[client_data5],
           t.[client_data6],
           t.[client_data7],
           t.[client_data8],
           t.[date_prepaid_check],
           t.[def_ordinal],
           t.[court_room2],
           t.[misc_1],
           t.[dob]
";

    /// <summary>Grid columns only. No nvarchar(max) column appears here.</summary>
    public const string GridColumns = @"
           t.[id],
           t.[client_id],
           t.[lawfirm_filenumber],
           t.[plaintiff],
           t.[defendant],
           t.[document_type],
           t.[index_number],
           t.[court_name],
           t.[servee_name],
           t.[client_ref],
           t.[creditor]
";

    public const string InsertStatement = @"
        INSERT INTO dbo.Import_Update
        ([id], [client_id], [lawfirm_filenumber], [3rdparty_filenumber], [plaintiff], [plaintiff2], [defendant], [defendant2], [document_code], [document_type], [index_number], [court_name], [court_type], [court_county], [court_city], [court_state], [court_zip], [servee_last_name], [servee_name], [servee_address], [servee_apt], [servee_city], [servee_state], [servee_zip], [servee_last_name2], [servee_name2], [servee_address2], [servee_apt2], [servee_city2], [servee_state2], [servee_zip2], [employer_name], [employer_address1], [employer_address2], [employer_city], [employer_state], [employer_zip], [special_instructions], [additional_info1], [additional_info2], [additional_info3], [additional_info4], [additional_info5], [kasebilling_checknum], [kasebilling_amt], [date_kase_filed], [court_date], [court_time], [court_room], [date_due], [client_ref], [creditor], [chargeoff_date], [suit_amt], [principal], [interest], [court_cost], [atty_cost], [client_data1], [client_data2], [client_data3], [client_data4], [client_data5], [client_data6], [client_data7], [client_data8], [date_prepaid_check], [def_ordinal], [court_room2], [misc_1], [dob])
        VALUES
        (@id, @client_id, @lawfirm_filenumber, @thirdparty_filenumber, @plaintiff, @plaintiff2, @defendant, @defendant2, @document_code, @document_type, @index_number, @court_name, @court_type, @court_county, @court_city, @court_state, @court_zip, @servee_last_name, @servee_name, @servee_address, @servee_apt, @servee_city, @servee_state, @servee_zip, @servee_last_name2, @servee_name2, @servee_address2, @servee_apt2, @servee_city2, @servee_state2, @servee_zip2, @employer_name, @employer_address1, @employer_address2, @employer_city, @employer_state, @employer_zip, @special_instructions, @additional_info1, @additional_info2, @additional_info3, @additional_info4, @additional_info5, @kasebilling_checknum, @kasebilling_amt, @date_kase_filed, @court_date, @court_time, @court_room, @date_due, @client_ref, @creditor, @chargeoff_date, @suit_amt, @principal, @interest, @court_cost, @atty_cost, @client_data1, @client_data2, @client_data3, @client_data4, @client_data5, @client_data6, @client_data7, @client_data8, @date_prepaid_check, @def_ordinal, @court_room2, @misc_1, @dob);";

    /// <summary>
    /// SET clause for update. [id] is excluded deliberately -- it identifies the row,
    /// and changing it would orphan the rows that reference it.
    /// </summary>
    public const string UpdateStatement = @"
        UPDATE dbo.Import_Update
           SET
               [client_id] = @client_id,
               [lawfirm_filenumber] = @lawfirm_filenumber,
               [3rdparty_filenumber] = @thirdparty_filenumber,
               [plaintiff] = @plaintiff,
               [plaintiff2] = @plaintiff2,
               [defendant] = @defendant,
               [defendant2] = @defendant2,
               [document_code] = @document_code,
               [document_type] = @document_type,
               [index_number] = @index_number,
               [court_name] = @court_name,
               [court_type] = @court_type,
               [court_county] = @court_county,
               [court_city] = @court_city,
               [court_state] = @court_state,
               [court_zip] = @court_zip,
               [servee_last_name] = @servee_last_name,
               [servee_name] = @servee_name,
               [servee_address] = @servee_address,
               [servee_apt] = @servee_apt,
               [servee_city] = @servee_city,
               [servee_state] = @servee_state,
               [servee_zip] = @servee_zip,
               [servee_last_name2] = @servee_last_name2,
               [servee_name2] = @servee_name2,
               [servee_address2] = @servee_address2,
               [servee_apt2] = @servee_apt2,
               [servee_city2] = @servee_city2,
               [servee_state2] = @servee_state2,
               [servee_zip2] = @servee_zip2,
               [employer_name] = @employer_name,
               [employer_address1] = @employer_address1,
               [employer_address2] = @employer_address2,
               [employer_city] = @employer_city,
               [employer_state] = @employer_state,
               [employer_zip] = @employer_zip,
               [special_instructions] = @special_instructions,
               [additional_info1] = @additional_info1,
               [additional_info2] = @additional_info2,
               [additional_info3] = @additional_info3,
               [additional_info4] = @additional_info4,
               [additional_info5] = @additional_info5,
               [kasebilling_checknum] = @kasebilling_checknum,
               [kasebilling_amt] = @kasebilling_amt,
               [date_kase_filed] = @date_kase_filed,
               [court_date] = @court_date,
               [court_time] = @court_time,
               [court_room] = @court_room,
               [date_due] = @date_due,
               [client_ref] = @client_ref,
               [creditor] = @creditor,
               [chargeoff_date] = @chargeoff_date,
               [suit_amt] = @suit_amt,
               [principal] = @principal,
               [interest] = @interest,
               [court_cost] = @court_cost,
               [atty_cost] = @atty_cost,
               [client_data1] = @client_data1,
               [client_data2] = @client_data2,
               [client_data3] = @client_data3,
               [client_data4] = @client_data4,
               [client_data5] = @client_data5,
               [client_data6] = @client_data6,
               [client_data7] = @client_data7,
               [client_data8] = @client_data8,
               [date_prepaid_check] = @date_prepaid_check,
               [def_ordinal] = @def_ordinal,
               [court_room2] = @court_room2,
               [misc_1] = @misc_1,
               [dob] = @dob
         WHERE id = @TargetId;";
}
