// <auto-generated>
//     Generated from the CREATE TABLE statement for [dbo].[ImportFileHeader].
//     64 columns. Regenerate rather than editing by hand.
// </auto-generated>

namespace ProVest.Admin.Api.Data;

/// <summary>
/// SQL fragments for [dbo].[ImportFileHeader]. Every value reaches the database as a
/// parameter; nothing here is built from user input.
/// </summary>
internal static class ImportFileHeaderSql
{
    public const string Table = "dbo.ImportFileHeader";
    public const string Alias = "t";

    /// <summary>All 64 columns, for the detail record.</summary>
    public const string DetailColumns = @"
           t.[id],
           t.[client_id],
           t.[col_1],
           t.[col_2],
           t.[col_3],
           t.[col_4],
           t.[col_5],
           t.[col_6],
           t.[col_7],
           t.[col_8],
           t.[col_9],
           t.[col_10],
           t.[col_11],
           t.[col_12],
           t.[col_13],
           t.[col_14],
           t.[col_15],
           t.[col_16],
           t.[col_17],
           t.[col_18],
           t.[col_19],
           t.[col_20],
           t.[col_21],
           t.[col_22],
           t.[col_23],
           t.[col_24],
           t.[col_25],
           t.[col_26],
           t.[col_27],
           t.[col_28],
           t.[col_29],
           t.[col_30],
           t.[col_31],
           t.[col_32],
           t.[col_33],
           t.[col_34],
           t.[col_35],
           t.[col_36],
           t.[col_37],
           t.[col_38],
           t.[col_39],
           t.[col_40],
           t.[col_41],
           t.[col_42],
           t.[col_43],
           t.[col_44],
           t.[col_45],
           t.[col_46],
           t.[col_47],
           t.[col_48],
           t.[col_49],
           t.[col_50],
           t.[col_51],
           t.[col_52],
           t.[col_53],
           t.[col_54],
           t.[col_55],
           t.[col_56],
           t.[col_57],
           t.[col_58],
           t.[col_59],
           t.[col_60],
           t.[importer_id],
           t.[unique_key]
";

    /// <summary>Grid columns only. No nvarchar(max) column appears here.</summary>
    public const string GridColumns = @"
           t.[id],
           t.[client_id],
           t.[importer_id],
           t.[col_1],
           t.[col_2],
           t.[col_3],
           t.[col_4],
           t.[col_5],
           t.[col_6],
           t.[col_7],
           t.[col_8],
           LEFT(t.[unique_key], 200) AS unique_key_preview
";

    public const string InsertStatement = @"
        INSERT INTO dbo.ImportFileHeader
        ([id], [client_id], [col_1], [col_2], [col_3], [col_4], [col_5], [col_6], [col_7], [col_8], [col_9], [col_10], [col_11], [col_12], [col_13], [col_14], [col_15], [col_16], [col_17], [col_18], [col_19], [col_20], [col_21], [col_22], [col_23], [col_24], [col_25], [col_26], [col_27], [col_28], [col_29], [col_30], [col_31], [col_32], [col_33], [col_34], [col_35], [col_36], [col_37], [col_38], [col_39], [col_40], [col_41], [col_42], [col_43], [col_44], [col_45], [col_46], [col_47], [col_48], [col_49], [col_50], [col_51], [col_52], [col_53], [col_54], [col_55], [col_56], [col_57], [col_58], [col_59], [col_60], [importer_id], [unique_key])
        VALUES
        (@id, @client_id, @col_1, @col_2, @col_3, @col_4, @col_5, @col_6, @col_7, @col_8, @col_9, @col_10, @col_11, @col_12, @col_13, @col_14, @col_15, @col_16, @col_17, @col_18, @col_19, @col_20, @col_21, @col_22, @col_23, @col_24, @col_25, @col_26, @col_27, @col_28, @col_29, @col_30, @col_31, @col_32, @col_33, @col_34, @col_35, @col_36, @col_37, @col_38, @col_39, @col_40, @col_41, @col_42, @col_43, @col_44, @col_45, @col_46, @col_47, @col_48, @col_49, @col_50, @col_51, @col_52, @col_53, @col_54, @col_55, @col_56, @col_57, @col_58, @col_59, @col_60, @importer_id, @unique_key);";

    /// <summary>
    /// SET clause for update. [id] is excluded deliberately -- it identifies the row,
    /// and changing it would orphan the rows that reference it.
    /// </summary>
    public const string UpdateStatement = @"
        UPDATE dbo.ImportFileHeader
           SET
               [client_id] = @client_id,
               [col_1] = @col_1,
               [col_2] = @col_2,
               [col_3] = @col_3,
               [col_4] = @col_4,
               [col_5] = @col_5,
               [col_6] = @col_6,
               [col_7] = @col_7,
               [col_8] = @col_8,
               [col_9] = @col_9,
               [col_10] = @col_10,
               [col_11] = @col_11,
               [col_12] = @col_12,
               [col_13] = @col_13,
               [col_14] = @col_14,
               [col_15] = @col_15,
               [col_16] = @col_16,
               [col_17] = @col_17,
               [col_18] = @col_18,
               [col_19] = @col_19,
               [col_20] = @col_20,
               [col_21] = @col_21,
               [col_22] = @col_22,
               [col_23] = @col_23,
               [col_24] = @col_24,
               [col_25] = @col_25,
               [col_26] = @col_26,
               [col_27] = @col_27,
               [col_28] = @col_28,
               [col_29] = @col_29,
               [col_30] = @col_30,
               [col_31] = @col_31,
               [col_32] = @col_32,
               [col_33] = @col_33,
               [col_34] = @col_34,
               [col_35] = @col_35,
               [col_36] = @col_36,
               [col_37] = @col_37,
               [col_38] = @col_38,
               [col_39] = @col_39,
               [col_40] = @col_40,
               [col_41] = @col_41,
               [col_42] = @col_42,
               [col_43] = @col_43,
               [col_44] = @col_44,
               [col_45] = @col_45,
               [col_46] = @col_46,
               [col_47] = @col_47,
               [col_48] = @col_48,
               [col_49] = @col_49,
               [col_50] = @col_50,
               [col_51] = @col_51,
               [col_52] = @col_52,
               [col_53] = @col_53,
               [col_54] = @col_54,
               [col_55] = @col_55,
               [col_56] = @col_56,
               [col_57] = @col_57,
               [col_58] = @col_58,
               [col_59] = @col_59,
               [col_60] = @col_60,
               [importer_id] = @importer_id,
               [unique_key] = @unique_key
         WHERE id = @TargetId;";
}
