// <auto-generated>
//     Generated from the CREATE TABLE statement for [dbo].[ImportFileHeader].
//     64 columns. Regenerate rather than editing by hand.
// </auto-generated>

// Files matching *.g.cs are treated as generated, which opts them out of the
// project's nullable context, so it is re-enabled explicitly here.
#nullable enable

using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace ProVest.Admin.Api.Contracts;

/// <summary>
/// ImportFileHeader holds one row per importer layout: col_1..col_60 are the raw
/// header row from the client file and unique_key is those headers concatenated,
/// which is what the importer matches on to resolve an ImporterId.
/// </summary>
public sealed class ImportFileHeaderListItem
{
    [JsonIgnore]
    public int TotalCount { get; set; }

    public int? id { get; set; }
    public int? client_id { get; set; }
    public int? importer_id { get; set; }
    public string? col_1 { get; set; }
    public string? col_2 { get; set; }
    public string? col_3 { get; set; }
    public string? col_4 { get; set; }
    public string? col_5 { get; set; }
    public string? col_6 { get; set; }
    public string? col_7 { get; set; }
    public string? col_8 { get; set; }
    /// <summary>First 200 characters of [unique_key]. The full value is nvarchar(max) and comes from GetById.</summary>
    public string? unique_key_preview { get; set; }

    /// <summary>
    /// False when [id] is null or shared with another row. This table has no primary
    /// key, so such a row cannot be targeted by an update or delete and the grid
    /// renders it read-only.
    /// </summary>
    public bool IsAddressable { get; set; }
}

public sealed class ImportFileHeaderDetail
{
    public int? id { get; set; }
    public int? client_id { get; set; }
    public string? col_1 { get; set; }
    public string? col_2 { get; set; }
    public string? col_3 { get; set; }
    public string? col_4 { get; set; }
    public string? col_5 { get; set; }
    public string? col_6 { get; set; }
    public string? col_7 { get; set; }
    public string? col_8 { get; set; }
    public string? col_9 { get; set; }
    public string? col_10 { get; set; }
    public string? col_11 { get; set; }
    public string? col_12 { get; set; }
    public string? col_13 { get; set; }
    public string? col_14 { get; set; }
    public string? col_15 { get; set; }
    public string? col_16 { get; set; }
    public string? col_17 { get; set; }
    public string? col_18 { get; set; }
    public string? col_19 { get; set; }
    public string? col_20 { get; set; }
    public string? col_21 { get; set; }
    public string? col_22 { get; set; }
    public string? col_23 { get; set; }
    public string? col_24 { get; set; }
    public string? col_25 { get; set; }
    public string? col_26 { get; set; }
    public string? col_27 { get; set; }
    public string? col_28 { get; set; }
    public string? col_29 { get; set; }
    public string? col_30 { get; set; }
    public string? col_31 { get; set; }
    public string? col_32 { get; set; }
    public string? col_33 { get; set; }
    public string? col_34 { get; set; }
    public string? col_35 { get; set; }
    public string? col_36 { get; set; }
    public string? col_37 { get; set; }
    public string? col_38 { get; set; }
    public string? col_39 { get; set; }
    public string? col_40 { get; set; }
    public string? col_41 { get; set; }
    public string? col_42 { get; set; }
    public string? col_43 { get; set; }
    public string? col_44 { get; set; }
    public string? col_45 { get; set; }
    public string? col_46 { get; set; }
    public string? col_47 { get; set; }
    public string? col_48 { get; set; }
    public string? col_49 { get; set; }
    public string? col_50 { get; set; }
    public string? col_51 { get; set; }
    public string? col_52 { get; set; }
    public string? col_53 { get; set; }
    public string? col_54 { get; set; }
    public string? col_55 { get; set; }
    public string? col_56 { get; set; }
    public string? col_57 { get; set; }
    public string? col_58 { get; set; }
    public string? col_59 { get; set; }
    public string? col_60 { get; set; }
    public int? importer_id { get; set; }
    public string? unique_key { get; set; }
}

public sealed class ImportFileHeaderListQuery : ListQuery
{
    public int? id { get; set; }
    public int? client_id { get; set; }
    public int? importer_id { get; set; }
}

/// <summary>
/// Used for both create and update. On update the target row is identified by the
/// route id and [id] itself is not modified -- changing it would orphan the
/// ProVestColumnMapping and ImportFileHeader rows that reference it.
/// </summary>
public sealed class ImportFileHeaderWriteRequest
{
    public int? id { get; set; }
    public int? client_id { get; set; }
    [MaxLength(500)]
    public string? col_1 { get; set; }
    [MaxLength(500)]
    public string? col_2 { get; set; }
    [MaxLength(500)]
    public string? col_3 { get; set; }
    [MaxLength(500)]
    public string? col_4 { get; set; }
    [MaxLength(500)]
    public string? col_5 { get; set; }
    [MaxLength(500)]
    public string? col_6 { get; set; }
    [MaxLength(500)]
    public string? col_7 { get; set; }
    [MaxLength(500)]
    public string? col_8 { get; set; }
    [MaxLength(500)]
    public string? col_9 { get; set; }
    [MaxLength(500)]
    public string? col_10 { get; set; }
    [MaxLength(500)]
    public string? col_11 { get; set; }
    [MaxLength(500)]
    public string? col_12 { get; set; }
    [MaxLength(500)]
    public string? col_13 { get; set; }
    [MaxLength(500)]
    public string? col_14 { get; set; }
    [MaxLength(500)]
    public string? col_15 { get; set; }
    [MaxLength(500)]
    public string? col_16 { get; set; }
    [MaxLength(500)]
    public string? col_17 { get; set; }
    [MaxLength(500)]
    public string? col_18 { get; set; }
    [MaxLength(500)]
    public string? col_19 { get; set; }
    [MaxLength(500)]
    public string? col_20 { get; set; }
    [MaxLength(500)]
    public string? col_21 { get; set; }
    [MaxLength(500)]
    public string? col_22 { get; set; }
    [MaxLength(500)]
    public string? col_23 { get; set; }
    [MaxLength(500)]
    public string? col_24 { get; set; }
    [MaxLength(500)]
    public string? col_25 { get; set; }
    [MaxLength(500)]
    public string? col_26 { get; set; }
    [MaxLength(500)]
    public string? col_27 { get; set; }
    [MaxLength(500)]
    public string? col_28 { get; set; }
    [MaxLength(500)]
    public string? col_29 { get; set; }
    [MaxLength(500)]
    public string? col_30 { get; set; }
    [MaxLength(500)]
    public string? col_31 { get; set; }
    [MaxLength(500)]
    public string? col_32 { get; set; }
    [MaxLength(500)]
    public string? col_33 { get; set; }
    [MaxLength(500)]
    public string? col_34 { get; set; }
    [MaxLength(500)]
    public string? col_35 { get; set; }
    [MaxLength(500)]
    public string? col_36 { get; set; }
    [MaxLength(500)]
    public string? col_37 { get; set; }
    [MaxLength(500)]
    public string? col_38 { get; set; }
    [MaxLength(500)]
    public string? col_39 { get; set; }
    [MaxLength(500)]
    public string? col_40 { get; set; }
    [MaxLength(500)]
    public string? col_41 { get; set; }
    [MaxLength(500)]
    public string? col_42 { get; set; }
    [MaxLength(500)]
    public string? col_43 { get; set; }
    [MaxLength(500)]
    public string? col_44 { get; set; }
    [MaxLength(500)]
    public string? col_45 { get; set; }
    [MaxLength(500)]
    public string? col_46 { get; set; }
    [MaxLength(500)]
    public string? col_47 { get; set; }
    [MaxLength(500)]
    public string? col_48 { get; set; }
    [MaxLength(500)]
    public string? col_49 { get; set; }
    [MaxLength(500)]
    public string? col_50 { get; set; }
    [MaxLength(500)]
    public string? col_51 { get; set; }
    [MaxLength(500)]
    public string? col_52 { get; set; }
    [MaxLength(500)]
    public string? col_53 { get; set; }
    [MaxLength(500)]
    public string? col_54 { get; set; }
    [MaxLength(500)]
    public string? col_55 { get; set; }
    [MaxLength(500)]
    public string? col_56 { get; set; }
    [MaxLength(500)]
    public string? col_57 { get; set; }
    [MaxLength(500)]
    public string? col_58 { get; set; }
    [MaxLength(500)]
    public string? col_59 { get; set; }
    [MaxLength(500)]
    public string? col_60 { get; set; }
    public int? importer_id { get; set; }
    public string? unique_key { get; set; }
}
