// <auto-generated>
//     Generated from the CREATE TABLE statement for [dbo].[Import_Update].
//     71 columns. Regenerate rather than editing by hand.
// </auto-generated>

// Files matching *.g.cs are treated as generated, which opts them out of the
// project's nullable context, so it is re-enabled explicitly here.
#nullable enable

using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace ProVest.Admin.Api.Contracts;

/// <summary>
/// Import_Update holds one row per importer layout. Each cell is the name of the
/// column in that client's raw file that feeds the corresponding ProVest standard
/// column -- these are header names, not case data.
/// </summary>
public sealed class ImportUpdateListItem
{
    [JsonIgnore]
    public int TotalCount { get; set; }

    public int? id { get; set; }
    public int? client_id { get; set; }
    public string? lawfirm_filenumber { get; set; }
    public string? plaintiff { get; set; }
    public string? defendant { get; set; }
    public string? document_type { get; set; }
    public string? index_number { get; set; }
    public string? court_name { get; set; }
    public string? servee_name { get; set; }
    public string? client_ref { get; set; }
    public string? creditor { get; set; }

    /// <summary>
    /// False when [id] is null or shared with another row. This table has no primary
    /// key, so such a row cannot be targeted by an update or delete and the grid
    /// renders it read-only.
    /// </summary>
    public bool IsAddressable { get; set; }
}

public sealed class ImportUpdateDetail
{
    public int? id { get; set; }
    public int? client_id { get; set; }
    public string? lawfirm_filenumber { get; set; }
    /// <summary>Database column [3rdparty_filenumber] -- renamed here because a C# identifier cannot start with a digit.</summary>
    [JsonPropertyName("3rdparty_filenumber")]
    public string? thirdparty_filenumber { get; set; }
    public string? plaintiff { get; set; }
    public string? plaintiff2 { get; set; }
    public string? defendant { get; set; }
    public string? defendant2 { get; set; }
    public string? document_code { get; set; }
    public string? document_type { get; set; }
    public string? index_number { get; set; }
    public string? court_name { get; set; }
    public string? court_type { get; set; }
    public string? court_county { get; set; }
    public string? court_city { get; set; }
    public string? court_state { get; set; }
    public string? court_zip { get; set; }
    public string? servee_last_name { get; set; }
    public string? servee_name { get; set; }
    public string? servee_address { get; set; }
    public string? servee_apt { get; set; }
    public string? servee_city { get; set; }
    public string? servee_state { get; set; }
    public string? servee_zip { get; set; }
    public string? servee_last_name2 { get; set; }
    public string? servee_name2 { get; set; }
    public string? servee_address2 { get; set; }
    public string? servee_apt2 { get; set; }
    public string? servee_city2 { get; set; }
    public string? servee_state2 { get; set; }
    public string? servee_zip2 { get; set; }
    public string? employer_name { get; set; }
    public string? employer_address1 { get; set; }
    public string? employer_address2 { get; set; }
    public string? employer_city { get; set; }
    public string? employer_state { get; set; }
    public string? employer_zip { get; set; }
    public string? special_instructions { get; set; }
    public string? additional_info1 { get; set; }
    public string? additional_info2 { get; set; }
    public string? additional_info3 { get; set; }
    public string? additional_info4 { get; set; }
    public string? additional_info5 { get; set; }
    public string? kasebilling_checknum { get; set; }
    public string? kasebilling_amt { get; set; }
    public string? date_kase_filed { get; set; }
    public string? court_date { get; set; }
    public string? court_time { get; set; }
    public string? court_room { get; set; }
    public string? date_due { get; set; }
    public string? client_ref { get; set; }
    public string? creditor { get; set; }
    public string? chargeoff_date { get; set; }
    public string? suit_amt { get; set; }
    public string? principal { get; set; }
    public string? interest { get; set; }
    public string? court_cost { get; set; }
    public string? atty_cost { get; set; }
    public string? client_data1 { get; set; }
    public string? client_data2 { get; set; }
    public string? client_data3 { get; set; }
    public string? client_data4 { get; set; }
    public string? client_data5 { get; set; }
    public string? client_data6 { get; set; }
    public string? client_data7 { get; set; }
    public string? client_data8 { get; set; }
    public string? date_prepaid_check { get; set; }
    public string? def_ordinal { get; set; }
    public string? court_room2 { get; set; }
    public string? misc_1 { get; set; }
    public string? dob { get; set; }
}

public sealed class ImportUpdateListQuery : ListQuery
{
    public int? id { get; set; }
    public int? client_id { get; set; }
}

/// <summary>
/// Used for both create and update. On update the target row is identified by the
/// route id and [id] itself is not modified -- changing it would orphan the
/// ProVestColumnMapping and ImportFileHeader rows that reference it.
/// </summary>
public sealed class ImportUpdateWriteRequest
{
    public int? id { get; set; }
    public int? client_id { get; set; }
    [MaxLength(500)]
    public string? lawfirm_filenumber { get; set; }
    /// <summary>Database column [3rdparty_filenumber] -- renamed here because a C# identifier cannot start with a digit.</summary>
    [JsonPropertyName("3rdparty_filenumber")]
    [MaxLength(500)]
    public string? thirdparty_filenumber { get; set; }
    [MaxLength(500)]
    public string? plaintiff { get; set; }
    [MaxLength(500)]
    public string? plaintiff2 { get; set; }
    [MaxLength(500)]
    public string? defendant { get; set; }
    [MaxLength(500)]
    public string? defendant2 { get; set; }
    [MaxLength(500)]
    public string? document_code { get; set; }
    [MaxLength(500)]
    public string? document_type { get; set; }
    [MaxLength(500)]
    public string? index_number { get; set; }
    [MaxLength(500)]
    public string? court_name { get; set; }
    [MaxLength(500)]
    public string? court_type { get; set; }
    [MaxLength(500)]
    public string? court_county { get; set; }
    [MaxLength(500)]
    public string? court_city { get; set; }
    [MaxLength(500)]
    public string? court_state { get; set; }
    [MaxLength(500)]
    public string? court_zip { get; set; }
    [MaxLength(500)]
    public string? servee_last_name { get; set; }
    [MaxLength(500)]
    public string? servee_name { get; set; }
    [MaxLength(500)]
    public string? servee_address { get; set; }
    [MaxLength(500)]
    public string? servee_apt { get; set; }
    [MaxLength(500)]
    public string? servee_city { get; set; }
    [MaxLength(500)]
    public string? servee_state { get; set; }
    [MaxLength(500)]
    public string? servee_zip { get; set; }
    [MaxLength(500)]
    public string? servee_last_name2 { get; set; }
    [MaxLength(500)]
    public string? servee_name2 { get; set; }
    [MaxLength(500)]
    public string? servee_address2 { get; set; }
    [MaxLength(500)]
    public string? servee_apt2 { get; set; }
    [MaxLength(500)]
    public string? servee_city2 { get; set; }
    [MaxLength(500)]
    public string? servee_state2 { get; set; }
    [MaxLength(500)]
    public string? servee_zip2 { get; set; }
    [MaxLength(500)]
    public string? employer_name { get; set; }
    [MaxLength(500)]
    public string? employer_address1 { get; set; }
    [MaxLength(500)]
    public string? employer_address2 { get; set; }
    [MaxLength(500)]
    public string? employer_city { get; set; }
    [MaxLength(500)]
    public string? employer_state { get; set; }
    [MaxLength(500)]
    public string? employer_zip { get; set; }
    public string? special_instructions { get; set; }
    [MaxLength(500)]
    public string? additional_info1 { get; set; }
    [MaxLength(500)]
    public string? additional_info2 { get; set; }
    [MaxLength(500)]
    public string? additional_info3 { get; set; }
    [MaxLength(500)]
    public string? additional_info4 { get; set; }
    [MaxLength(500)]
    public string? additional_info5 { get; set; }
    [MaxLength(500)]
    public string? kasebilling_checknum { get; set; }
    [MaxLength(500)]
    public string? kasebilling_amt { get; set; }
    [MaxLength(500)]
    public string? date_kase_filed { get; set; }
    [MaxLength(500)]
    public string? court_date { get; set; }
    [MaxLength(500)]
    public string? court_time { get; set; }
    [MaxLength(500)]
    public string? court_room { get; set; }
    [MaxLength(500)]
    public string? date_due { get; set; }
    [MaxLength(500)]
    public string? client_ref { get; set; }
    [MaxLength(500)]
    public string? creditor { get; set; }
    [MaxLength(500)]
    public string? chargeoff_date { get; set; }
    [MaxLength(500)]
    public string? suit_amt { get; set; }
    [MaxLength(500)]
    public string? principal { get; set; }
    [MaxLength(500)]
    public string? interest { get; set; }
    [MaxLength(500)]
    public string? court_cost { get; set; }
    [MaxLength(500)]
    public string? atty_cost { get; set; }
    [MaxLength(500)]
    public string? client_data1 { get; set; }
    [MaxLength(500)]
    public string? client_data2 { get; set; }
    [MaxLength(500)]
    public string? client_data3 { get; set; }
    [MaxLength(500)]
    public string? client_data4 { get; set; }
    [MaxLength(500)]
    public string? client_data5 { get; set; }
    [MaxLength(500)]
    public string? client_data6 { get; set; }
    [MaxLength(500)]
    public string? client_data7 { get; set; }
    [MaxLength(500)]
    public string? client_data8 { get; set; }
    [MaxLength(500)]
    public string? date_prepaid_check { get; set; }
    [MaxLength(500)]
    public string? def_ordinal { get; set; }
    [MaxLength(500)]
    public string? court_room2 { get; set; }
    [MaxLength(500)]
    public string? misc_1 { get; set; }
    [MaxLength(500)]
    public string? dob { get; set; }
}
